name: spemlGPU
channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.9
  - pip
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - pip:
      - watermark
      - tensorboard
      - jupyterlab
      - tqdm
      - opencv-python
      - seaborn
      - albumentations
      - Pillow
      - h5py
      - scipy
      - plotly
      - torchfile
