# General experiment settings
# Example:
# dataset: CIFAR-10
# architecture: GoogleNet
# learning_rate: 0.001
# epochs: 50
# batch_size: 64
# attack_type: fine_tuning
# attack_params:
#   epochs: 10
#   learning_rate: 0.0001
